# __Clean Data__

In [85]:
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('../raw/eval.csv',sep=';')


data.head()

,FDS,Nombre del Producto,Fabricante,Uso,Fecha Elaboración,Item_1_0,Calidad_1_0,Item_1_1,Calidad_1_1,Item_1_2,...,Item_14_6,Calidad_14_6,Item_15_0,Calidad_15_0,Item_15_1,Calidad_15_1,Item_16_0,Calidad_16_0,Item_16_1,Calidad_16_1
0,2,PRODUCTO 1 - INDUSTRIAL - FABRICANTE 1,FABRICANTE 1,Industrial,20/09/20,Presente,NO_Conf,Presente,Conf_CR,Presente,...,Presente,Confiable,Presente,Confiable,Presente,NO_Conf,Presente,Confiable,Presente,Conf_CR
1,4,PRODUCTO 2 - INDUSTRIAL - FABRICANTE 1,FABRICANTE 1,Industrial,28/02/20,Presente,NO_Conf,Presente,Conf_CR,Presente,...,Presente,Confiable,Presente,Confiable,Presente,NO_Conf,Presente,Confiable,Presente,Conf_CR
2,6,PRODUCTO 3 - INDUSTRIAL - FABRICANTE 1,FABRICANTE 1,Industrial,28/02/20,Presente,NO_Conf,Presente,Conf_CR,Presente,...,Presente,Confiable,Presente,Confiable,Presente,NO_Conf,Presente,Confiable,Presente,Conf_CR
3,25,PRODUCTO 4 - INDUSTRIAL - FABRICANTE 1,FABRICANTE 1,Industrial,4/01/20,Presente,NO_Conf,Presente,Conf_CR,Presente,...,Presente,Confiable,Presente,Confiable,Presente,NO_Conf,Presente,Confiable,Presente,Conf_CR
4,27,PRODUCTO 5 - INDUSTRIAL - FABRICANTE 1,FABRICANTE 1,Industrial,5/06/20,Presente,NO_Conf,Presente,Conf_CR,Presente,...,Presente,Confiable,Presente,Confiable,Presente,NO_Conf,Presente,Confiable,Presente,Conf_CR

In [86]:
data["FDS"] = data["FDS"].astype("Int64")
data.head()

,FDS,Nombre del Producto,Fabricante,Uso,Fecha Elaboración,Item_1_0,Calidad_1_0,Item_1_1,Calidad_1_1,Item_1_2,...,Item_14_6,Calidad_14_6,Item_15_0,Calidad_15_0,Item_15_1,Calidad_15_1,Item_16_0,Calidad_16_0,Item_16_1,Calidad_16_1
0,2,PRODUCTO 1 - INDUSTRIAL - FABRICANTE 1,FABRICANTE 1,Industrial,20/09/20,Presente,NO_Conf,Presente,Conf_CR,Presente,...,Presente,Confiable,Presente,Confiable,Presente,NO_Conf,Presente,Confiable,Presente,Conf_CR
1,4,PRODUCTO 2 - INDUSTRIAL - FABRICANTE 1,FABRICANTE 1,Industrial,28/02/20,Presente,NO_Conf,Presente,Conf_CR,Presente,...,Presente,Confiable,Presente,Confiable,Presente,NO_Conf,Presente,Confiable,Presente,Conf_CR
2,6,PRODUCTO 3 - INDUSTRIAL - FABRICANTE 1,FABRICANTE 1,Industrial,28/02/20,Presente,NO_Conf,Presente,Conf_CR,Presente,...,Presente,Confiable,Presente,Confiable,Presente,NO_Conf,Presente,Confiable,Presente,Conf_CR
3,25,PRODUCTO 4 - INDUSTRIAL - FABRICANTE 1,FABRICANTE 1,Industrial,4/01/20,Presente,NO_Conf,Presente,Conf_CR,Presente,...,Presente,Confiable,Presente,Confiable,Presente,NO_Conf,Presente,Confiable,Presente,Conf_CR
4,27,PRODUCTO 5 - INDUSTRIAL - FABRICANTE 1,FABRICANTE 1,Industrial,5/06/20,Presente,NO_Conf,Presente,Conf_CR,Presente,...,Presente,Confiable,Presente,Confiable,Presente,NO_Conf,Presente,Confiable,Presente,Conf_CR

In [87]:
import pandas as pd

col = "Nombre del Producto"  # ajusta si tu columna se llama distinto

s = (
    data[col]
    .astype(str)
    .str.upper()
    .str.replace(r"\s+", " ", regex=True)   # aplana saltos de línea/espacios
)

# Extrae números
prod = pd.to_numeric(s.str.extract(r"PRODUCTO\s*(\d+)", expand=False), errors="coerce")
fab  = pd.to_numeric(s.str.extract(r"FABRICANTE\s*(\d+)", expand=False), errors="coerce")

# Tipo: I si contiene INDUSTRIAL, si no -> D (puedes hacerlo más estricto si quieres)
tipo = s.str.contains(r"\bINDUSTRIAL\b", regex=True).map({True: "I", False: "D"})

# Construye el id
data["id"] = (
    "F" + fab.astype("Int64").astype(str).str.zfill(2) +
    "-P" + prod.astype("Int64").astype(str).str.zfill(2) +
    "-" + tipo
)
data["id"].head(51)

# 1) borrar la columna
data = data.drop(columns=["Nombre del Producto"])

In [88]:
data.head()

,FDS,Fabricante,Uso,Fecha Elaboración,Item_1_0,Calidad_1_0,Item_1_1,Calidad_1_1,Item_1_2,Calidad_1_2,...,Calidad_14_6,Item_15_0,Calidad_15_0,Item_15_1,Calidad_15_1,Item_16_0,Calidad_16_0,Item_16_1,Calidad_16_1,id
0,2,FABRICANTE 1,Industrial,20/09/20,Presente,NO_Conf,Presente,Conf_CR,Presente,Conf_CR,...,Confiable,Presente,Confiable,Presente,NO_Conf,Presente,Confiable,Presente,Conf_CR,F01-P01-I
1,4,FABRICANTE 1,Industrial,28/02/20,Presente,NO_Conf,Presente,Conf_CR,Presente,Conf_CR,...,Confiable,Presente,Confiable,Presente,NO_Conf,Presente,Confiable,Presente,Conf_CR,F01-P02-I
2,6,FABRICANTE 1,Industrial,28/02/20,Presente,NO_Conf,Presente,Conf_CR,Presente,Conf_CR,...,Confiable,Presente,Confiable,Presente,NO_Conf,Presente,Confiable,Presente,Conf_CR,F01-P03-I
3,25,FABRICANTE 1,Industrial,4/01/20,Presente,NO_Conf,Presente,Conf_CR,Presente,Conf_CR,...,Confiable,Presente,Confiable,Presente,NO_Conf,Presente,Confiable,Presente,Conf_CR,F01-P04-I
4,27,FABRICANTE 1,Industrial,5/06/20,Presente,NO_Conf,Presente,Conf_CR,Presente,Conf_CR,...,Confiable,Presente,Confiable,Presente,NO_Conf,Presente,Confiable,Presente,Conf_CR,F01-P05-I

In [89]:
# 1) Cambiar nombre de columna: Fabricante -> fabricante
data = data.rename(columns={"Fabricante": "fabricante"})

# 2) En 'fabricante': cambiar "FABRICANTE X" -> "FX"
#    (soporta espacios variables y mayúsc/minúsc; deja NaN intactos)
data["fabricante"] = (
    data["fabricante"]
    .astype(str)
    .str.upper()
    .str.replace(r"\s+", " ", regex=True)
    .str.replace(r"^FABRICANTE\s*(\d+)$", r"F\1", regex=True)
)

data["fabricante"] = data["fabricante"].str.replace(r"^F(\d+)$", lambda m: f"F{int(m.group(1)):02d}", regex=True)

# 3) En Uso: renombrar columna a USO y pasar valores a mayúscula
data = data.rename(columns={"Uso": "USO"})
data["USO"] = data["USO"].astype(str).str.upper()

In [90]:
data.head()

,FDS,fabricante,USO,Fecha Elaboración,Item_1_0,Calidad_1_0,Item_1_1,Calidad_1_1,Item_1_2,Calidad_1_2,...,Calidad_14_6,Item_15_0,Calidad_15_0,Item_15_1,Calidad_15_1,Item_16_0,Calidad_16_0,Item_16_1,Calidad_16_1,id
0,2,F01,INDUSTRIAL,20/09/20,Presente,NO_Conf,Presente,Conf_CR,Presente,Conf_CR,...,Confiable,Presente,Confiable,Presente,NO_Conf,Presente,Confiable,Presente,Conf_CR,F01-P01-I
1,4,F01,INDUSTRIAL,28/02/20,Presente,NO_Conf,Presente,Conf_CR,Presente,Conf_CR,...,Confiable,Presente,Confiable,Presente,NO_Conf,Presente,Confiable,Presente,Conf_CR,F01-P02-I
2,6,F01,INDUSTRIAL,28/02/20,Presente,NO_Conf,Presente,Conf_CR,Presente,Conf_CR,...,Confiable,Presente,Confiable,Presente,NO_Conf,Presente,Confiable,Presente,Conf_CR,F01-P03-I
3,25,F01,INDUSTRIAL,4/01/20,Presente,NO_Conf,Presente,Conf_CR,Presente,Conf_CR,...,Confiable,Presente,Confiable,Presente,NO_Conf,Presente,Confiable,Presente,Conf_CR,F01-P04-I
4,27,F01,INDUSTRIAL,5/06/20,Presente,NO_Conf,Presente,Conf_CR,Presente,Conf_CR,...,Confiable,Presente,Confiable,Presente,NO_Conf,Presente,Confiable,Presente,Conf_CR,F01-P05-I

In [91]:
import numpy as np

mapa = {
    "presente": "PRESENTE",
    "no present": "AUSENTE",
}

def normaliza_valor(x):
    if isinstance(x, str):
        k = " ".join(x.strip().lower().split())  # quita espacios extra y normaliza
        return mapa.get(k, x)                    # solo cambia si coincide
    return x

data = data.apply(lambda col: col.map(normaliza_valor))

In [92]:
data.head()

,FDS,fabricante,USO,Fecha Elaboración,Item_1_0,Calidad_1_0,Item_1_1,Calidad_1_1,Item_1_2,Calidad_1_2,...,Calidad_14_6,Item_15_0,Calidad_15_0,Item_15_1,Calidad_15_1,Item_16_0,Calidad_16_0,Item_16_1,Calidad_16_1,id
0,2,F01,INDUSTRIAL,20/09/20,PRESENTE,NO_Conf,PRESENTE,Conf_CR,PRESENTE,Conf_CR,...,Confiable,PRESENTE,Confiable,PRESENTE,NO_Conf,PRESENTE,Confiable,PRESENTE,Conf_CR,F01-P01-I
1,4,F01,INDUSTRIAL,28/02/20,PRESENTE,NO_Conf,PRESENTE,Conf_CR,PRESENTE,Conf_CR,...,Confiable,PRESENTE,Confiable,PRESENTE,NO_Conf,PRESENTE,Confiable,PRESENTE,Conf_CR,F01-P02-I
2,6,F01,INDUSTRIAL,28/02/20,PRESENTE,NO_Conf,PRESENTE,Conf_CR,PRESENTE,Conf_CR,...,Confiable,PRESENTE,Confiable,PRESENTE,NO_Conf,PRESENTE,Confiable,PRESENTE,Conf_CR,F01-P03-I
3,25,F01,INDUSTRIAL,4/01/20,PRESENTE,NO_Conf,PRESENTE,Conf_CR,PRESENTE,Conf_CR,...,Confiable,PRESENTE,Confiable,PRESENTE,NO_Conf,PRESENTE,Confiable,PRESENTE,Conf_CR,F01-P04-I
4,27,F01,INDUSTRIAL,5/06/20,PRESENTE,NO_Conf,PRESENTE,Conf_CR,PRESENTE,Conf_CR,...,Confiable,PRESENTE,Confiable,PRESENTE,NO_Conf,PRESENTE,Confiable,PRESENTE,Conf_CR,F01-P05-I

In [93]:
mapa2 = {
    "confiable": "CONFIABLE",
    "no_conf": "NO_CONFIABLE",
    "conf_cr": "CONFI_RESTR",
}

def normaliza_valor_2(x):
    if isinstance(x, str):
        k = " ".join(x.strip().lower().split())
        return mapa2.get(k, x)
    return x

cols_texto = data.select_dtypes(include=["object", "string"]).columns
data[cols_texto] = data[cols_texto].apply(lambda col: col.map(normaliza_valor_2))

In [94]:
data.head()

,FDS,fabricante,USO,Fecha Elaboración,Item_1_0,Calidad_1_0,Item_1_1,Calidad_1_1,Item_1_2,Calidad_1_2,...,Calidad_14_6,Item_15_0,Calidad_15_0,Item_15_1,Calidad_15_1,Item_16_0,Calidad_16_0,Item_16_1,Calidad_16_1,id
0,2,F01,INDUSTRIAL,20/09/20,PRESENTE,NO_CONFIABLE,PRESENTE,CONFI_RESTR,PRESENTE,CONFI_RESTR,...,CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,NO_CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,CONFI_RESTR,F01-P01-I
1,4,F01,INDUSTRIAL,28/02/20,PRESENTE,NO_CONFIABLE,PRESENTE,CONFI_RESTR,PRESENTE,CONFI_RESTR,...,CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,NO_CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,CONFI_RESTR,F01-P02-I
2,6,F01,INDUSTRIAL,28/02/20,PRESENTE,NO_CONFIABLE,PRESENTE,CONFI_RESTR,PRESENTE,CONFI_RESTR,...,CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,NO_CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,CONFI_RESTR,F01-P03-I
3,25,F01,INDUSTRIAL,4/01/20,PRESENTE,NO_CONFIABLE,PRESENTE,CONFI_RESTR,PRESENTE,CONFI_RESTR,...,CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,NO_CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,CONFI_RESTR,F01-P04-I
4,27,F01,INDUSTRIAL,5/06/20,PRESENTE,NO_CONFIABLE,PRESENTE,CONFI_RESTR,PRESENTE,CONFI_RESTR,...,CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,NO_CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,CONFI_RESTR,F01-P05-I

In [95]:
data["Fecha Elaboración"] = pd.to_datetime(
    data["Fecha Elaboración"],
    format="%d/%m/%y",
    dayfirst=True
)
data.head()

,FDS,fabricante,USO,Fecha Elaboración,Item_1_0,Calidad_1_0,Item_1_1,Calidad_1_1,Item_1_2,Calidad_1_2,...,Calidad_14_6,Item_15_0,Calidad_15_0,Item_15_1,Calidad_15_1,Item_16_0,Calidad_16_0,Item_16_1,Calidad_16_1,id
0,2,F01,INDUSTRIAL,2020-09-20,PRESENTE,NO_CONFIABLE,PRESENTE,CONFI_RESTR,PRESENTE,CONFI_RESTR,...,CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,NO_CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,CONFI_RESTR,F01-P01-I
1,4,F01,INDUSTRIAL,2020-02-28,PRESENTE,NO_CONFIABLE,PRESENTE,CONFI_RESTR,PRESENTE,CONFI_RESTR,...,CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,NO_CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,CONFI_RESTR,F01-P02-I
2,6,F01,INDUSTRIAL,2020-02-28,PRESENTE,NO_CONFIABLE,PRESENTE,CONFI_RESTR,PRESENTE,CONFI_RESTR,...,CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,NO_CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,CONFI_RESTR,F01-P03-I
3,25,F01,INDUSTRIAL,2020-01-04,PRESENTE,NO_CONFIABLE,PRESENTE,CONFI_RESTR,PRESENTE,CONFI_RESTR,...,CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,NO_CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,CONFI_RESTR,F01-P04-I
4,27,F01,INDUSTRIAL,2020-06-05,PRESENTE,NO_CONFIABLE,PRESENTE,CONFI_RESTR,PRESENTE,CONFI_RESTR,...,CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,NO_CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,CONFI_RESTR,F01-P05-I

In [96]:
data = data.rename(columns={
    "Fecha Elaboración": "elaborada",
    "USO": "uso",
})

In [97]:
data.head()

,FDS,fabricante,uso,elaborada,Item_1_0,Calidad_1_0,Item_1_1,Calidad_1_1,Item_1_2,Calidad_1_2,...,Calidad_14_6,Item_15_0,Calidad_15_0,Item_15_1,Calidad_15_1,Item_16_0,Calidad_16_0,Item_16_1,Calidad_16_1,id
0,2,F01,INDUSTRIAL,2020-09-20,PRESENTE,NO_CONFIABLE,PRESENTE,CONFI_RESTR,PRESENTE,CONFI_RESTR,...,CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,NO_CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,CONFI_RESTR,F01-P01-I
1,4,F01,INDUSTRIAL,2020-02-28,PRESENTE,NO_CONFIABLE,PRESENTE,CONFI_RESTR,PRESENTE,CONFI_RESTR,...,CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,NO_CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,CONFI_RESTR,F01-P02-I
2,6,F01,INDUSTRIAL,2020-02-28,PRESENTE,NO_CONFIABLE,PRESENTE,CONFI_RESTR,PRESENTE,CONFI_RESTR,...,CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,NO_CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,CONFI_RESTR,F01-P03-I
3,25,F01,INDUSTRIAL,2020-01-04,PRESENTE,NO_CONFIABLE,PRESENTE,CONFI_RESTR,PRESENTE,CONFI_RESTR,...,CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,NO_CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,CONFI_RESTR,F01-P04-I
4,27,F01,INDUSTRIAL,2020-06-05,PRESENTE,NO_CONFIABLE,PRESENTE,CONFI_RESTR,PRESENTE,CONFI_RESTR,...,CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,NO_CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,CONFI_RESTR,F01-P05-I

In [98]:
primeras = ["FDS", "elaborada", "id", "fabricante", "uso"]

data = data[primeras + [c for c in data.columns if c not in primeras]]

In [99]:
data.head()

,FDS,elaborada,id,fabricante,uso,Item_1_0,Calidad_1_0,Item_1_1,Calidad_1_1,Item_1_2,...,Item_14_6,Calidad_14_6,Item_15_0,Calidad_15_0,Item_15_1,Calidad_15_1,Item_16_0,Calidad_16_0,Item_16_1,Calidad_16_1
0,2,2020-09-20,F01-P01-I,F01,INDUSTRIAL,PRESENTE,NO_CONFIABLE,PRESENTE,CONFI_RESTR,PRESENTE,...,PRESENTE,CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,NO_CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,CONFI_RESTR
1,4,2020-02-28,F01-P02-I,F01,INDUSTRIAL,PRESENTE,NO_CONFIABLE,PRESENTE,CONFI_RESTR,PRESENTE,...,PRESENTE,CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,NO_CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,CONFI_RESTR
2,6,2020-02-28,F01-P03-I,F01,INDUSTRIAL,PRESENTE,NO_CONFIABLE,PRESENTE,CONFI_RESTR,PRESENTE,...,PRESENTE,CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,NO_CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,CONFI_RESTR
3,25,2020-01-04,F01-P04-I,F01,INDUSTRIAL,PRESENTE,NO_CONFIABLE,PRESENTE,CONFI_RESTR,PRESENTE,...,PRESENTE,CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,NO_CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,CONFI_RESTR
4,27,2020-06-05,F01-P05-I,F01,INDUSTRIAL,PRESENTE,NO_CONFIABLE,PRESENTE,CONFI_RESTR,PRESENTE,...,PRESENTE,CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,NO_CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,CONFI_RESTR

In [100]:
import re

def normaliza_col(c):
    c2 = c.strip()
    c2 = re.sub(r"^Item_", "ITEM_", c2, flags=re.IGNORECASE)
    c2 = re.sub(r"^Calidad_", "CALIDAD_", c2, flags=re.IGNORECASE)
    return c2.upper()

data = data.rename(columns={c: normaliza_col(c) for c in data.columns})

In [101]:
data.head()

,FDS,ELABORADA,ID,FABRICANTE,USO,ITEM_1_0,CALIDAD_1_0,ITEM_1_1,CALIDAD_1_1,ITEM_1_2,...,ITEM_14_6,CALIDAD_14_6,ITEM_15_0,CALIDAD_15_0,ITEM_15_1,CALIDAD_15_1,ITEM_16_0,CALIDAD_16_0,ITEM_16_1,CALIDAD_16_1
0,2,2020-09-20,F01-P01-I,F01,INDUSTRIAL,PRESENTE,NO_CONFIABLE,PRESENTE,CONFI_RESTR,PRESENTE,...,PRESENTE,CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,NO_CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,CONFI_RESTR
1,4,2020-02-28,F01-P02-I,F01,INDUSTRIAL,PRESENTE,NO_CONFIABLE,PRESENTE,CONFI_RESTR,PRESENTE,...,PRESENTE,CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,NO_CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,CONFI_RESTR
2,6,2020-02-28,F01-P03-I,F01,INDUSTRIAL,PRESENTE,NO_CONFIABLE,PRESENTE,CONFI_RESTR,PRESENTE,...,PRESENTE,CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,NO_CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,CONFI_RESTR
3,25,2020-01-04,F01-P04-I,F01,INDUSTRIAL,PRESENTE,NO_CONFIABLE,PRESENTE,CONFI_RESTR,PRESENTE,...,PRESENTE,CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,NO_CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,CONFI_RESTR
4,27,2020-06-05,F01-P05-I,F01,INDUSTRIAL,PRESENTE,NO_CONFIABLE,PRESENTE,CONFI_RESTR,PRESENTE,...,PRESENTE,CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,NO_CONFIABLE,PRESENTE,CONFIABLE,PRESENTE,CONFI_RESTR

In [104]:
import re
import pandas as pd

texto = r"""
1.0. 	Título: Identificación del producto
1.1.	Identificador SGA del producto
1.2.	Otros medios de identificación
1.3.	Uso recomendado del producto químico y restricciones de uso
1.4.	Datos del proveedor 
1.5.	Número de teléfono para emergencias 
2.0. 	Título: Identificación del peligro o peligros
2.1.	Clasificación  SGA  de  la  sustancia/mezcla  y  cualquier  información nacional o regional
2.1.1. 	Elementos de la etiqueta SGA: Pictogramas
2.1.2. 	Elementos de la etiqueta SGA: Palabra de Advertencia
2.1.3. 	Elementos de la etiqueta SGA: Indicaciones de Peligro
2.1.4. 	Elementos de la etiqueta SGA Consejos de Prudencia
2.2. 	Otros peligros que no figuren en la clasificación (por ejemplo, peligro de explosión de partículas de polvo) o que no están cubiertos por el SGA
3.0. 	Título: Composición/información sobre los componentes
3.1.1. 	Identidad química de la sustancia 
3.1.1.1.	Nombres comunes o sinónimos de la sustancia 
3.1.1.2.	Número CAS y otros identificadores únicos de la sustancia 
3.1.1.3.	Impurezas, aditivos o estabilizadores presentes en la sustancia 
3.2.1. 	Identidad química de la sustancia 
3.2.1.1.	Nombres comunes o sinónimos de la mezcla
3.2.1.2.	Número CAS y otros identificadores únicos de la mezcla
3.2.1.3. 	Concentración o gamas de concentraciones de todos los componentes de la mezcla 
4.0. 	Título: Primeros auxilios
4.1.	Descripción de las medidas necesarias, desglosadas con arreglo a las diferentes vías de exposición, esto es, inhalación, contacto cutáneo y ocular e ingestión
4.2.	Síntomas/efectos más importantes, agudos y retardados
4.3.	Indicación de la necesidad de recibir atención médica inmediata y tratamiento especial requerido en caso necesario
5.0.	Título: Medidas de lucha contra incendios
5.1.	Medios adecuados (o no adecuados) de extinción
5.2.	Peligros específicos del producto químico
5.3.	Medidas especiales que deben tomar los equipos de lucha contra incendios
6.0.	Título: Medidas que deben tomarse en caso de vertido accidental
6.1.	Precauciones individuales, equipos de protección y procedimientos de emergencia
6.2.	Precauciones relativas al medio ambiente 
6.3.	Métodos y materiales para la contención y limpieza de vertidos
7.0.	Título: Manipulación y almacenamiento
7.1.	Precauciones que se deben tomar para garantizar una manipulación segura
7.2.	Condiciones   de   almacenamiento   seguro,   incluidas   cualesquiera incompatibilidades
8.0.	Controles de exposición/protección personal
8.1.	Parámetros  de  control:  límites  o  valores  de  corte  de  exposición ocupacionales o biológicos
8.2.	Controles técnicos apropiados
8.3.	Medidas  de  protección  individual,  como  equipos  de  protección personal
9.0.	Título: Propiedades físicas y químicas
9.1. 	Propiedades fisicas y químicas 
10.0.	Título: Estabilidad y reactividad
10.1. 	Reactividad 
10.2. 	Estabilidad química 
10.3. 	Posibilidad de reacciones peligrosas
10.4. 	Condiciones que deben evitarse 
10.5. 	Materiales incompatibles 
10.6. 	Productos de descomposición peligrosos
11.0.	Título: Información toxicológica 
11.1. 	Efectos toxicológicos 
11.2. 	Información sobre las posibles vías de exposición 
11.3. 	Síntomas relacionados con las características físicas, químicas y toxicológicas 
11.4.	Efectos inmediatos y retardados así como efectos crónicos producidos por una exposición a corto y largo plazo
11.5. 	Medidas numéricas de toxicidad (tales como estimaciones de toxicidad aguda) 
12.0.	Título: Información ecotoxicológica
12.1. 	Toxicidad 
12.2. 	Persistencia y degradabilidad 
12.3. 	Potencial de bioacumulación 
12.4.	Movilidad en el suelo
12.5. 	Otros efectos adversos
13.0.	Título: Información relativa a la eliminación de los productos 
13.1. 	Métodos de eliminación 
14.0.	Título: Información relativa al transporte 
14.1. 	Número ONU 
14.2. 	Designación oficial de transporte de las Naciones Unidas
14.3. 	Clase(s) relativas al transporte
14.4. 	Grupo de embalaje/envasado si se aplica
14.5. 	Riesgos ambientales
14.6. 	Precauciones especiales para el usuario 
15.0.	Título: Información sobre la reglamentación
15.1. 	Disposiciones específicas sobre seguridad, salud y medio ambiente para el producto de que se trate
16.0.	Título: Otras informaciones 
16.1. 	Otras informaciones 
"""

line_pat = re.compile(r"^\s*(\d+(?:\.\d+)+)\.\s*(.+?)\s*$")
titulo_pat = re.compile(r"^\s*T[ÍI]TULO\s*:\s*(.+)\s*$", re.IGNORECASE)

# meta para tu esquema actual X_Y (solo dos niveles: seccion.subitem)
meta = {}      # clave "15_1", "15_0", ...
meta_full = {} # clave "3_1_1_2" para subniveles profundos (por si lo quieres)

titulo_seccion_actual = {}

for raw in texto.splitlines():
    raw = raw.strip()
    if not raw:
        continue

    m = line_pat.match(raw)
    if not m:
        continue

    codigo = m.group(1)  # ej "15.1" o "3.1.1.2"
    desc = m.group(2).strip()

    partes = codigo.split(".")
    seccion = int(partes[0])

    # título de sección
    mt = titulo_pat.match(desc)
    if mt and len(partes) == 2 and int(partes[1]) == 0:
        titulo = mt.group(1).strip()
        titulo_seccion_actual[seccion] = titulo
        key = f"{seccion}_0"
        meta[key] = {"seccion": seccion, "subitem": 0, "titulo_seccion": titulo, "item": None, "codigo": codigo}
        meta_full["_".join(partes)] = {"titulo_seccion": titulo, "item": None, "codigo": codigo}
        continue

    # si no es título, guarda el item
    titulo = titulo_seccion_actual.get(seccion)

    # meta_full siempre lo guarda (para 2.1.1, 3.1.1.2, etc.)
    meta_full["_".join(partes)] = {"titulo_seccion": titulo, "item": desc, "codigo": codigo}

    # meta (solo 2 niveles) solo guarda si es X.Y (ej 15.1)
    if len(partes) == 2:
        subitem = int(partes[1])
        key = f"{seccion}_{subitem}"
        meta[key] = {"seccion": seccion, "subitem": subitem, "titulo_seccion": titulo, "item": desc, "codigo": codigo}

# DataFrame de referencia para tu esquema actual (X_Y)
df_meta = (
    pd.DataFrame.from_dict(meta, orient="index")
      .reset_index(names="key")  # key = "15_1"
      .sort_values(["seccion", "subitem"])
      .reset_index(drop=True)
)

df_meta.head(20)

,key,seccion,subitem,titulo_seccion,item,codigo
0,1_0,1,0,Identificación del producto,NaN,1.0
1,1_1,1,1,Identificación del producto,Identificador SGA del producto,1.1
2,1_2,1,2,Identificación del producto,Otros medios de identificación,1.2
3,1_3,1,3,Identificación del producto,Uso recomendado del producto químico y restric...,1.3
4,1_4,1,4,Identificación del producto,Datos del proveedor,1.4
5,1_5,1,5,Identificación del producto,Número de teléfono para emergencias,1.5
6,2_0,2,0,Identificación del peligro o peligros,NaN,2.0
7,2_1,2,1,Identificación del peligro o peligros,Clasificación SGA de la sustancia/mezcla ...,2.1
8,2_2,2,2,Identificación del peligro o peligros,Otros peligros que no figuren en la clasificac...,2.2
9,3_0,3,0,Composición/información sobre los componentes,NaN,3.0
10,4_0,4,0,Primeros auxilios,NaN,4.0
11,4_1,4,1,Primeros auxilios,"Descripción de las medidas necesarias, desglos...",4.1
12,4_2,4,2,Primeros auxilios,"Síntomas/efectos más importantes, agudos y ret...",4.2
13,4_3,4,3,Primeros auxilios,Indicación de la necesidad de recibir atención...,4.3
14,5_0,5,0,Medidas de lucha contra incendios,NaN,5.0
15,5_1,5,1,Medidas de lucha contra incendios,Medios adecuados (o no adecuados) de extinción,5.1
16,5_2,5,2,Medidas de lucha contra incendios,Peligros específicos del producto químico,5.2
17,5_3,5,3,Medidas de lucha contra incendios,Medidas especiales que deben tomar los equipos...,5.3
18,6_0,6,0,Medidas que deben tomarse en caso de vertido a...,NaN,6.0
19,6_1,6,1,Medidas que deben tomarse en caso de vertido a...,"Precauciones individuales, equipos de protecci...",6.1

In [106]:
import re

def describe_col(col):
    m = re.match(r"^(ITEM|CALIDAD)_(\d+)_(\d+)$", col, flags=re.IGNORECASE)
    if not m:
        return None
    key = f"{int(m.group(2))}_{int(m.group(3))}"
    return meta.get(key)

describe_col("ITEM_3_1_1_1")